import { BadgeIndianRupee, Clock3, Headphones, LockKeyhole, MapPin, MessageCircle, Phone, UserRoundCheck, Zap, CheckCircle2, ChevronDown, Star, Navigation } from 'lucide-react'
import { useState } from 'react'
import { business, faqs, serviceGroups, testimonials } from '../data/siteData'
import { CallButton, SectionTitle, track, WhatsAppButton, whatsappUrl } from './Common'

export function TrustSection(){const items=[[Zap,'Fast Service'],[LockKeyhole,'Secure & Confidential'],[BadgeIndianRupee,'Transparent Pricing'],[UserRoundCheck,'Personal Assistance'],[Headphones,'Local Customer Support']];return <section className="border-y border-slate-200 bg-white py-12"><div className="section-shell"><h2 className="mb-7 text-center text-xl font-black text-slate-950 md:text-2xl">Why Customers Choose Shri Balaji Digital & Business Services</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{items.map(([Icon,t]:any)=><div key={t} className="rounded-2xl border border-slate-200 bg-slate-50 p-5 text-center"><Icon className="mx-auto mb-3 text-blue-700"/><p className="font-bold">{t}</p></div>)}</div></div></section>}

export function Services(){return <section id="services" className="py-20"><div className="section-shell"><SectionTitle eyebrow="Services" title="Our Digital & Business Services" text="Everything you need, under one roof. Services can be edited from one central data file as your business grows."/>{serviceGroups.map((g,gi)=><div key={g.title} className={gi?'mt-12':''}><h3 className="mb-5 text-2xl font-black text-slate-950">{g.title}</h3><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{g.items.map(([name,desc],i)=><article key={name} className="group rounded-3xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-soft"><div className="mb-4 grid h-11 w-11 place-items-center rounded-2xl bg-blue-50 font-black text-blue-700">{String(i+1).padStart(2,'0')}</div><h4 className="text-lg font-black">{name}</h4><p className="mt-2 min-h-12 text-sm leading-6 text-slate-600">{desc}</p><a href={whatsappUrl()} onClick={()=>track('whatsapp_click',{service:name})} className="mt-5 inline-flex items-center gap-2 font-bold text-emerald-700 hover:text-emerald-800"><MessageCircle size={18}/> Enquire on WhatsApp</a></article>)}</div></div>)}</div></section>}

export function CTASection(){return <section className="py-6"><div className="section-shell"><div className="overflow-hidden rounded-[2rem] bg-gradient-to-r from-slate-950 via-blue-950 to-blue-800 p-7 text-white md:p-10"><div className="grid items-center gap-6 md:grid-cols-[1fr_auto]"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-orange-400">Need assistance?</p><h2 className="mt-2 text-3xl font-black">Need Help With an Online or Digital Service?</h2><p className="mt-3 text-blue-100">Tell us what you need. We'll guide you through the process.</p><p className="mt-3 text-sm font-semibold text-blue-100">Quick response • Transparent pricing • Personal assistance</p></div><div className="flex flex-col gap-3 sm:flex-row md:flex-col"><WhatsAppButton label="WhatsApp Now"/><CallButton label="Call Us"/></div></div></div></div></section>}

export function Process(){const steps=[['01','Contact Us','Call or WhatsApp us with your requirement.'],['02','Share Details','Provide the required information/documents securely.'],['03','We Process Your Request','Our team assists with the required digital/business service.'],['04','Get It Done','Receive confirmation, documents or completion details.']];return <section id="process" className="bg-white py-20"><div className="section-shell"><SectionTitle eyebrow="Simple Process" title="How It Works" text="A clear, human process designed to save you time and confusion."/><div className="grid gap-5 md:grid-cols-4">{steps.map(([n,t,d])=><div key={n} className="relative rounded-3xl border border-slate-200 p-6"><div className="mb-6 text-5xl font-black text-blue-100">{n}</div><h3 className="text-lg font-black">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{d}</p></div>)}</div></div></section>}

export function WhyChooseUs(){const items=[['One-Stop Service','Multiple digital and business services available at one place.'],['Personal Assistance','Get human assistance instead of struggling with complicated online processes.'],['Transparent Pricing','Service charges are communicated before starting work.'],['Fast Response','Quick response through phone and WhatsApp.'],['Privacy First','Customer documents and information should be handled responsibly and confidentially.'],['Local & Reliable','Built around local trust and long-term customer relationships.']];return <section id="why-us" className="py-20"><div className="section-shell"><SectionTitle eyebrow="Why Us" title="Why Choose Shri Balaji Digital & Business Services?"/><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{items.map(([t,d])=><div key={t} className="rounded-3xl border border-slate-200 bg-white p-6"><CheckCircle2 className="mb-4 text-emerald-600"/><h3 className="text-lg font-black">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{d}</p></div>)}</div></div></section>}

export function AboutLocal(){return <section id="about" className="bg-slate-950 py-20 text-white"><div className="section-shell grid gap-10 lg:grid-cols-[1fr_.9fr]"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-orange-400">Local trust</p><h2 className="mt-3 text-4xl font-black">Your Local Digital Service Partner</h2><p className="mt-5 max-w-2xl leading-8 text-slate-300">From online applications to business documentation and digital assistance, Shri Balaji Digital & Business Services helps local customers complete important tasks quickly and conveniently.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#contact" className="inline-flex items-center gap-2 rounded-xl bg-orange-500 px-5 py-3 font-bold hover:bg-orange-600"><Navigation size={18}/> Get Directions</a><WhatsAppButton/></div></div><div className="grid gap-3">{[[MapPin,'Service Area',business.serviceArea],[Phone,'Phone',business.phone],[MessageCircle,'WhatsApp',business.whatsapp],[Clock3,'Business Hours',business.hours]].map(([Icon,l,v]:any)=><div key={l} className="flex gap-4 rounded-2xl border border-white/10 bg-white/5 p-4"><Icon className="text-orange-400"/><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{l}</p><p className="mt-1 font-semibold">{v}</p></div></div>)}<div className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Email</p><p className="mt-1 font-semibold">{business.email}</p></div></div></div></section>}

export function Testimonials(){return <section className="py-20"><div className="section-shell"><SectionTitle eyebrow="Testimonials" title="What Our Customers Say" text="Replace these placeholders only with genuine reviews from verified customers."/><div className="grid gap-5 md:grid-cols-3">{testimonials.map((t,i)=><article key={i} className="rounded-3xl border border-slate-200 bg-white p-6"><div className="mb-4 flex gap-1 text-amber-500">{Array.from({length:t.rating}).map((_,i)=><Star key={i} size={17} fill="currentColor"/>)}</div><p className="text-slate-700">“{t.review}”</p><div className="mt-6 border-t border-slate-100 pt-4"><p className="font-black">{t.name}</p><p className="text-sm text-slate-500">{t.service}</p></div></article>)}</div><p className="mt-5 text-center text-xs font-semibold text-slate-500">Customer reviews should be published only after verification.</p></div></section>}

export function FAQ(){const [open,setOpen]=useState<number|null>(0);return <section id="faq" className="bg-white py-20"><div className="section-shell"><SectionTitle eyebrow="FAQ" title="Frequently Asked Questions"/><div className="mx-auto max-w-3xl divide-y divide-slate-200 rounded-3xl border border-slate-200 bg-white px-5">{faqs.map(([q,a],i)=><div key={q} className="py-2"><button onClick={()=>setOpen(open===i?null:i)} className="flex w-full items-center justify-between gap-4 py-4 text-left font-black" aria-expanded={open===i}>{q}<ChevronDown className={`shrink-0 transition ${open===i?'rotate-180':''}`}/></button>{open===i&&<p className="pb-5 text-sm leading-6 text-slate-600">{a}</p>}</div>)}</div></div></section>}
